# Generated by Django 2.2.3 on 2019-07-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Pic',
            new_name='image',
        ),
    ]
